In [8]:
 import numpy as np
    # np.random.normal(mu, sigma, size)
normal_array = np.random.normal(79, 15, 80)
normal_array



array([ 67.50891724,  72.89005186,  95.45117286,  85.36115898,
        71.93268533,  86.83792569,  87.41600931, 111.57074767,
        64.54179064, 126.09083235,  89.75312368,  89.02012293,
        82.11778331,  65.06940855,  94.89811193,  72.48806291,
        80.09857279,  81.29068083, 111.56475372,  67.49098692,
        58.37796096,  65.64193685,  84.297826  ,  54.060561  ,
       105.64564623,  78.83191553,  62.64045632,  52.51811183,
        87.35285791, 110.99393818,  77.88466293,  53.87032914,
        94.07527201,  73.84849988,  96.1245307 ,  48.37264311,
        93.25710871,  58.29394125,  84.9913567 ,  96.32883709,
        61.87633097,  63.3230729 ,  69.21377066,  87.46371644,
        73.93840695,  95.74450711,  72.3467869 ,  66.10799355,
        73.27327077,  75.83316287, 103.51650488,  75.39133298,
        65.52723474,  63.36213591,  91.44993077,  97.15191922,
        89.97104038,  61.50547267,  62.34052926,  79.35900746,
        74.41812365,  66.9310718 ,  65.60297862,  83.86

In [ ]:
,

In [12]:
np.asarray(four_by_four_matrix)[2] = 2
four_by_four_matrix

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [1., 1., 1., 1.]])

In [13]:
# creating list using range(starting, stop, step)
lst = range(0, 11, 2)
lst
range(0, 11, 2)
for l in lst:
    print(l)

0
2
4
6
8
10


In [14]:
# Similar to range arange numpy.arange(start, stop, step)
whole_numbers = np.arange(0, 20, 1)
whole_numbers

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [16]:
Odd_numbers =np.arange(1,20,2)
Odd_numbers

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [19]:
Even_numbers = np.arange(0,20,2)
Even_numbers

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [20]:
Natural_numbers = np.arange(1,20,1)
Natural_numbers


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [23]:
np_normal_dis = np.random.normal(5, 0.5, 100)
np_normal_dis

NameError: name 'np_normal_' is not defined